### PR TITLE
Fixups for Provider documentation

### PR DESCRIPTION
**Pull request by sapid**
- Add `:::tip`s to not include quotes in variable values for provider environment variables
- Remove quotes from the provider environment variable screenshot
- Minor typographical fixup

### CODE REVIEW

**Comment by sapid** [comment]
Ah, nuts. I signed these commits wrong. One moment...

**Comment by sapid** [comment]
All set.

**Comment by gregtwallace** [comment]
I'm working on an update to make the quoting thing a non-issue if people use quotes or double quotes. Might as well fix the underlying problem since `MY_VAR="Some_value-I-Want"` is a pretty standard format for this type of thing.

**Comment by gregtwallace** [comment]
Thank you.

**Pull request merged**
